_target_: src.models.gcpnet_ema_module.GCPNetEMALitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with PyTorch 2.0
compile: false

# `ProteinWorkshop` encoder-decoder model config
defaults:
  - model_cfg: structure_denoising_pretrained_gcpnet.yaml
