# @package _global_

defaults:
  - _self_
  - data: ema # choose datamodule with `test_dataloader()` for evaluation
  - model: gcpnet_ema
  - logger: null
  - strategy: default
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - environment: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
