# @package _global_

defaults:
  - data: ema # choose datamodule with `predict_dataloader()` for prediction
  - model: gcpnet_ema
  - logger: null
  - strategy: default
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - environment: default
  - _self_

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for prediction
ckpt_path: ???

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# note: for WandB logging from certain remote GPU servers
create_unverified_ssl_context: false

# arguments to override
model:
  ablate_af2_plddt: true
