apiVersion: batch/v1
kind: Job
metadata:
  name: run-gcpnet-ema-ablate-pt-weights-and-plddt
spec:
  backoffLimit: 0
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      # NOTE: we select 24GB GPUs only here
                      - NVIDIA-A10
                      - NVIDIA-GeForce-RTX-3090
                      - NVIDIA-TITAN-RTX
                      - NVIDIA-RTX-A5000
                      - Quadro-RTX-6000
      containers:
        - command:
            - bash
            - -c
            - cd /data/Repositories/Lab_Repositories/GCPNet-EMA
              && WANDB__SERVICE_WAIT=3600 TRANSFORMERS_CACHE=/data/Transformers_Cache_Dir /data/Repositories/Lab_Repositories/GCPNet-EMA/GCPNet-EMA/bin/python src/train.py
              experiment=gcpnet_ema logger=wandb logger.wandb.id=ekxu8bgw logger.wandb.name=11102023_10_00_Run_GCPNet_EMA_Ablate_PT_Weights_And_plDDT
              hydra.run.dir=logs/train/runs/ekxu8bgw data.load_esm_model=false data.load_ankh_model=false model.model_cfg.finetune.encoder.load_weights=false data.ablate_af2_plddt=true
          env:
            - name: NCCL_SOCKET_IFNAME
              value: eth0
            - name: NCCL_DEBUG
              value: INFO
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: acmwhb-wandb-secret
                  key: secret
          image: gitlab-registry.nrp-nautilus.io/bioinfomachinelearning/bio-diffusion:bb558b48
          imagePullPolicy: IfNotPresent
          name: bio-diffusion
          ports:
            - containerPort: 8880
          resources:
            limits:
              cpu: 1
              memory: 8Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 1
              memory: 6Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /data
              name: acmwhb-gcpnet-pvc-aux-11
            - mountPath: /dev/shm
              name: dshm
          workingDir: /data/Repositories/Lab_Repositories/GCPNet-EMA
      imagePullSecrets:
        - name: regcred-bio-diffusion
      restartPolicy: Never
      volumes:
        - name: acmwhb-gcpnet-pvc-aux-11
          persistentVolumeClaim:
            claimName: acmwhb-gcpnet-pvc-aux-11
        - emptyDir:
            medium: Memory
          name: dshm
